In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.DataFrame({
    "A": [10,20,30,40,50],
    "B": ['a', 'b', 'c', 'd', 'e']

})

,A,B
0,10,a
1,20,b
2,30,c
3,40,d
4,50,e


In [ ]:
df = pd.DataFrame({
    "A": [10,20,30,40,50],
    "B": ['a', 'b', 'c', 'd', 'e']

})

In [ ]:
df

,A,B
0,10,a
1,20,b
2,30,c
3,40,d
4,50,e


In [ ]:
pd.DataFrame({
    "A": [10,20,30,40,50],
    "B": ['a', 'b', 'c', 'd', 'e'],
    "C": np.random.randint(0,9,5)
})

,A,B,C
0,10,a,3
1,20,b,2
2,30,c,2
3,40,d,2
4,50,e,7


In [ ]:
pd.DataFrame(
    np.random.randint(0,9,(10, 4)), columns=["A", "B", "C", "D"]
)

,A,B,C,D
0,0,4,7,6
1,3,0,8,0
2,2,1,8,2
3,2,7,4,3
4,7,3,2,3
5,5,3,7,4
6,3,8,5,2
7,5,5,7,3
8,8,2,7,6
9,2,1,5,3


In [ ]:
np.random.rand(10,3).round(2)

array([[0.32, 0.66, 0.99],
       [0.72, 0.54, 0.62],
       [0.05, 0.74, 0.64],
       [0.28, 0.5 , 0.05],
       [0.01, 0.84, 0.42],
       [0.32, 0.89, 0.48],
       [0.48, 0.01, 0.6 ],
       [0.04, 0.14, 0.75],
       [0.39, 0.66, 0.86],
       [0.78, 0.08, 0.09]])

In [ ]:
# create the dataframe
dfx = pd.DataFrame(np.random.rand(100,3).round(2), columns=["AA", "BB", "CC"])

In [ ]:
dfx

,AA,BB,CC
0,0.13,0.66,0.11
1,0.80,0.16,0.33
2,0.33,0.94,0.59
3,0.31,0.44,0.01
4,0.11,0.19,0.24
...,...,...,...
95,0.08,0.74,0.98
96,0.61,0.09,0.69
97,0.51,0.41,0.69
98,0.06,0.32,0.62


In [ ]:
dfx.to_excel("abcd.xlsx") # store this file

In [4]:
df = pd.read_excel("abcd.xlsx", index_col="Unnamed: 0")

In [5]:
df

,AA,BB,CC
0,0.13,0.66,0.11
1,0.80,0.16,0.33
2,0.33,0.94,0.59
3,0.31,0.44,0.01
4,0.11,0.19,0.24
...,...,...,...
95,0.08,0.74,0.98
96,0.61,0.09,0.69
97,0.51,0.41,0.69
98,0.06,0.32,0.62


In [6]:
df['DD'] = np.random.randint(0,9,100)

In [7]:
df

,AA,BB,CC,DD
0,0.13,0.66,0.11,6
1,0.80,0.16,0.33,8
2,0.33,0.94,0.59,6
3,0.31,0.44,0.01,4
4,0.11,0.19,0.24,2
...,...,...,...,...
95,0.08,0.74,0.98,5
96,0.61,0.09,0.69,3
97,0.51,0.41,0.69,5
98,0.06,0.32,0.62,7


In [8]:
df['MM'] = np.random.choice(["cat", "dog"], 100)

In [9]:
df

,AA,BB,CC,DD,MM
0,0.13,0.66,0.11,6,dog
1,0.80,0.16,0.33,8,cat
2,0.33,0.94,0.59,6,cat
3,0.31,0.44,0.01,4,cat
4,0.11,0.19,0.24,2,dog
...,...,...,...,...,...
95,0.08,0.74,0.98,5,dog
96,0.61,0.09,0.69,3,cat
97,0.51,0.41,0.69,5,dog
98,0.06,0.32,0.62,7,dog


In [ ]:
df.describe(include='all')

,AA,BB,CC,DD,MM
count,100.000000,100.000000,100.000000,100.000000,100
unique,NaN,NaN,NaN,NaN,2
top,NaN,NaN,NaN,NaN,dog
freq,NaN,NaN,NaN,NaN,51
mean,0.472700,0.531700,0.534800,4.060000,NaN
std,0.271099,0.298034,0.294088,2.489655,NaN
min,0.010000,0.000000,0.000000,0.000000,NaN
25%,0.267500,0.317500,0.280000,2.000000,NaN
50%,0.475000,0.525000,0.585000,4.000000,NaN
75%,0.682500,0.805000,0.802500,6.000000,NaN


In [ ]:
df.drop('MM', axis=1)

,AA,BB,CC,DD
0,0.13,0.66,0.11,6
1,0.80,0.16,0.33,4
2,0.33,0.94,0.59,6
3,0.31,0.44,0.01,6
4,0.11,0.19,0.24,4
...,...,...,...,...
95,0.08,0.74,0.98,2
96,0.61,0.09,0.69,3
97,0.51,0.41,0.69,3
98,0.06,0.32,0.62,0


In [10]:
df

,AA,BB,CC,DD,MM
0,0.13,0.66,0.11,6,dog
1,0.80,0.16,0.33,8,cat
2,0.33,0.94,0.59,6,cat
3,0.31,0.44,0.01,4,cat
4,0.11,0.19,0.24,2,dog
...,...,...,...,...,...
95,0.08,0.74,0.98,5,dog
96,0.61,0.09,0.69,3,cat
97,0.51,0.41,0.69,5,dog
98,0.06,0.32,0.62,7,dog


In [11]:
dnx = df.drop('MM', axis=1)

In [12]:
dnx

,AA,BB,CC,DD
0,0.13,0.66,0.11,6
1,0.80,0.16,0.33,8
2,0.33,0.94,0.59,6
3,0.31,0.44,0.01,4
4,0.11,0.19,0.24,2
...,...,...,...,...
95,0.08,0.74,0.98,5
96,0.61,0.09,0.69,3
97,0.51,0.41,0.69,5
98,0.06,0.32,0.62,7


In [ ]:
# df.drop('MM', axis=1, inplace=True)

In [ ]:
dnx

,AA,BB,CC,DD
0,0.13,0.66,0.11,6
1,0.80,0.16,0.33,4
2,0.33,0.94,0.59,6
3,0.31,0.44,0.01,6
4,0.11,0.19,0.24,4
...,...,...,...,...
95,0.08,0.74,0.98,2
96,0.61,0.09,0.69,3
97,0.51,0.41,0.69,3
98,0.06,0.32,0.62,0


# How to use conditions to create a new column

In [ ]:
def find_big_small(x):
    if x > 5:
        print("big")
    else:
        print("small")

In [ ]:
dnx['DD'].apply(find_big_small)

In [ ]:
dnx['DD'].apply(lambda x: 'big' if x >= 5 else 'small')

,DD
0,big
1,small
2,big
3,big
4,small
...,...
95,small
96,small
97,small
98,small


In [ ]:
dnx

,AA,BB,CC,DD
0,0.13,0.66,0.11,6
1,0.80,0.16,0.33,4
2,0.33,0.94,0.59,6
3,0.31,0.44,0.01,6
4,0.11,0.19,0.24,4
...,...,...,...,...
95,0.08,0.74,0.98,2
96,0.61,0.09,0.69,3
97,0.51,0.41,0.69,3
98,0.06,0.32,0.62,0


In [ ]:
dnx['MM'] = dnx['DD'].apply(lambda x: 'big' if x >= 5 else 'small')

In [ ]:
dnx

,AA,BB,CC,DD,MM
0,0.13,0.66,0.11,6,big
1,0.80,0.16,0.33,4,small
2,0.33,0.94,0.59,6,big
3,0.31,0.44,0.01,6,big
4,0.11,0.19,0.24,4,small
...,...,...,...,...,...
95,0.08,0.74,0.98,2,small
96,0.61,0.09,0.69,3,small
97,0.51,0.41,0.69,3,small
98,0.06,0.32,0.62,0,small


In [ ]:
# dnx.drop(5)

,AA,BB,CC,DD,MM
0,0.13,0.66,0.11,6,big
1,0.80,0.16,0.33,4,small
2,0.33,0.94,0.59,6,big
3,0.31,0.44,0.01,6,big
4,0.11,0.19,0.24,4,small
...,...,...,...,...,...
95,0.08,0.74,0.98,2,small
96,0.61,0.09,0.69,3,small
97,0.51,0.41,0.69,3,small
98,0.06,0.32,0.62,0,small


# Indexing

In [ ]:
np.arange(10, 1001, 10)

array([  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
        120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,
        230,  240,  250,  260,  270,  280,  290,  300,  310,  320,  330,
        340,  350,  360,  370,  380,  390,  400,  410,  420,  430,  440,
        450,  460,  470,  480,  490,  500,  510,  520,  530,  540,  550,
        560,  570,  580,  590,  600,  610,  620,  630,  640,  650,  660,
        670,  680,  690,  700,  710,  720,  730,  740,  750,  760,  770,
        780,  790,  800,  810,  820,  830,  840,  850,  860,  870,  880,
        890,  900,  910,  920,  930,  940,  950,  960,  970,  980,  990,
       1000])

In [ ]:
dnx.set_index(np.arange(10,1001,10), inplace=True)

In [ ]:
dnx

,AA,BB,CC,DD,MM
10,0.13,0.66,0.11,6,big
20,0.80,0.16,0.33,4,small
30,0.33,0.94,0.59,6,big
40,0.31,0.44,0.01,6,big
50,0.11,0.19,0.24,4,small
...,...,...,...,...,...
960,0.08,0.74,0.98,2,small
970,0.61,0.09,0.69,3,small
980,0.51,0.41,0.69,3,small
990,0.06,0.32,0.62,0,small


In [ ]:
# dnx.loc[row name, column name]
# dnx.iloc[index of row name, index of column name]

In [ ]:
dnx.loc[990, 'CC']

np.float64(0.62)

In [ ]:
dnx.iloc[2, -1]

'big'

# Range of Index

In [13]:
st = "this is python"

In [20]:
st[2:12:3]

'iiph'

In [23]:
ar = np.random.randint(11, 99, (4,5,6))

In [24]:
ar

array([[[59, 33, 40, 16, 31, 28],
        [45, 23, 19, 73, 98, 72],
        [45, 36, 55, 70, 68, 97],
        [68, 77, 94, 48, 20, 47],
        [80, 77, 95, 80, 93, 61]],

       [[72, 96, 34, 74, 36, 19],
        [13, 29, 90, 22, 71, 48],
        [36, 80, 60, 50, 59, 43],
        [60, 33, 26, 61, 89, 26],
        [38, 91, 43, 78, 36, 37]],

       [[19, 61, 16, 71, 60, 18],
        [31, 63, 23, 73, 76, 98],
        [76, 21, 24, 75, 29, 44],
        [60, 42, 91, 88, 82, 71],
        [64, 36, 38, 84, 56, 92]],

       [[93, 78, 76, 81, 67, 69],
        [79, 75, 30, 59, 84, 30],
        [55, 93, 97, 41, 54, 65],
        [66, 78, 73, 27, 90, 20],
        [42, 72, 15, 37, 78, 28]]])

In [27]:
ar[2,3,:]

array([60, 42, 91, 88, 82, 71])

In [31]:
ar[2,:,2]

array([16, 23, 24, 91, 38])

In [32]:
ar[:,3,:]

array([[68, 77, 94, 48, 20, 47],
       [60, 33, 26, 61, 89, 26],
       [60, 42, 91, 88, 82, 71],
       [66, 78, 73, 27, 90, 20]])

In [33]:
ar[:,:,2]

array([[40, 19, 55, 94, 95],
       [34, 90, 60, 26, 43],
       [16, 23, 24, 91, 38],
       [76, 30, 97, 73, 15]])